from pessoa import Pessoa
p1 = Pessoa('João', 16)
p2 = Pessoa('Luiz', 35)
print(p2.nome)
p1.comer('Pão')
p1.comer('Pão')
p1.parar_comer()
p1.comer('Pão')
p1.falar('Futebol')
p1.parar_comer()
p1.falar('Futebol')
p1.falar('Jogos')
p1.parar_falar()
p1.parar_falar()
print(p1.ano)